// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface SaleWebhook {
  product: Product;
  commissions: Commission[];
  purchase: Purchase;
  affiliates: Affiliate[];
  producer: Producer;
  subscription: Subscription;
  buyer: Buyer;
  id: string;
  creation_date: number;
  event: string;
  version: string;
}

export interface Affiliate {
  affiliate_code: string;
  name: string;
}

export interface Buyer {
  address: Address;
  name: string;
  checkout_phone: string;
  email: string;
}

export interface Address {
  country: string;
  country_iso: string;
}

export interface Commission {
  currency_value: string;
  source: string;
  value: number;
}

export interface Producer {
  name: string;
}

export interface Product {
  has_co_production: boolean;
  name: string;
  id: number;
  ucode: string;
}

export interface Purchase {
  offer: Offer;
  order_date: number;
  original_offer_price: Price;
  price: Price;
  checkout_country: CheckoutCountry;
  sckPaymentLink: string;
  order_bump: OrderBump;
  payment: Payment;
  approved_date: number;
  full_price: Price;
  transaction: string;
  status: string;
}

export interface CheckoutCountry {
  iso: string;
  name: string;
}

export interface Price {
  currency_value: string;
  value: number;
}

export interface Offer {
  code: string;
}

export interface OrderBump {
  parent_purchase_transaction: string;
  is_order_bump: boolean;
}

export interface Payment {
  installments_number: number;
  type: string;
}

export interface Subscription {
  subscriber: Offer;
  plan: Plan;
  status: string;
}

export interface Plan {
  name: string;
  id: number;
}
